version: "3.9"

services:
  hugo:
    build:
      context: ..
      dockerfile: docker/Dockerfile.hugo
    ports:
      - "1313:1313"
    volumes:
      - ../hugo-site:/site

  cms:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cms
    volumes:
      - ../hugo-site:/app/hugo
    depends_on:
      - hugo