// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateSection(arg1:string):Promise<void>;

export function DeleteArticle(arg1:string):Promise<void>;

export function GetArticle(arg1:string):Promise<main.Article>;

export function GetSections():Promise<Array<main.Section>>;

export function ListArticles():Promise<Array<main.Article>>;

export function SaveArticle(arg1:main.Article):Promise<void>;
