// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSection(arg1) {
  return window['go']['main']['App']['CreateSection'](arg1);
}

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function GetArticle(arg1) {
  return window['go']['main']['App']['GetArticle'](arg1);
}

export function GetSections() {
  return window['go']['main']['App']['GetSections']();
}

export function ListArticles() {
  return window['go']['main']['App']['ListArticles']();
}

export function SaveArticle(arg1) {
  return window['go']['main']['App']['SaveArticle'](arg1);
}
